version: '3.9'

services:
    oracle-ords: 
        image: ords
        container_name: ords
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - './${ORDS_BASE_DIR}/ords/${ORDS_VERSION}/config:/opt/ords'
            - './${ORDS_BASE_DIR}/files/apex/${APEX_VERSION}/images:/ords/apex-images'
        ports:
            - '${ORDS_HTTP_PORT}:${ORDS_HTTP_PORT}'
        command: sh -c "/ords/config-run-ords.sh"
        healthcheck:
            test: curl --fail http://localhost:${ORDS_HTTP_PORT}/ords || exit 1
            interval: 5s
            retries: 5
            start_period: 10s
        networks:
            - oracle_network

networks:
    oracle_network:
        name: oracle_network
