version: '3.3'
services:
    oracle-ords:
        image: ords
        container_name: ords
        environment:
            - TZ=${TZ}
            - DB_HOSTNAME=${DB_HOSTNAME}
            - DB_PORT=${DB_PORT}
            - DB_SERVICENAME=${DB_SERVICENAME}
            - APEX_PUBLIC_USER_PASS=${APEX_PUBLIC_USER_PASS}
            - APEX_LISTENER_PASS=${APEX_LISTENER_PASS}
            - APEX_REST_PASS=${APEX_REST_PASS}
            - ORDS_PASS=${ORDS_PASS}
            - SYS_PASS=${SYS_PASS}
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '${ORDS_BASE_DIR}/ords/${ORDS_VERSION}/config:/opt/ords'
            - '${ORDS_BASE_DIR}/files/apex/${APEX_VERSION}/images:/ords/apex-images'
        ports:
            - '${ORDS_HTTP_PORT}:${ORDS_HTTP_PORT}'
